### ISSUE TITLE
(XMem.cpp line 721): Cannot allocate the memory

### ISSUE THREAD

**Issue by zqp2009happy** [NiuTrans/NiuTrans.NMT#2]
Hi, it's an amazing project, but I cannot start work with myself data which has a bigger vocabulary size about 40000. The error is  "(XMem.cpp line 721): Cannot allocate the memory", and my log is :
  8  -nepoch=50
  9  -maxcheckpoint=10
 10  -enclayer=9
 11  -declayer=1
 12  -embsize=256
 13  -modelsize=256
 14  -nhead=8
 15  -maxpos=128
 16
 17 encoder layer: 9
 18 decoder layer: 1
 19 attention heads: 8
 20 model size: 256
 21 source vocab size: 41056
 22 target vocab size: 41056
 23 [INFO] loaded 160239 sentences
 24 [ERROR] (XMem.cpp line 721): Cannot allocate the memory.
 25 terminate called without an active exception
 26 scripts/train.deen.sh: line 28:  1006 Aborted                 bin/NiuTrans.NMT -dev ${deviceID} -model $modelFile -train ${dataDir}/train.bin -valid ${dataDir}/valid.bin -nepoch 50 -maxcheckpoint 10 -enclayer 9 -declayer 1 -embsize 256 -modelsize 256 -nhead 8 -maxpos 128

Could you help me solve this problem?

**Comment by huchinlp** [comment]
Hi,

Thanks for your attention!

It seems that the memory footprint is too high for a memory block
(currently 256MB).
This can be solved by using a larger block size:
set MIN_BLOCK_SIZE_FOR_MEMPOOL to a larger number in
*source/niutensor/tensor/XMem.h:63*.

We are exploring better solutions, such as supporting users to specify the
size of the memory space.

In addition, high memory usage during training is a known issue, and we are
actively addressing it.

Best,

Chi Hu

zqp2009happy <notifications@github.com> 于2020年9月25日周五 上午9:49写道：

**Comment by zqp2009happy** [comment]
Thank you for your response. 
I modify: #define MIN_BLOCK_NUM_FOR_MEMPOOL 1024 * 1024 * 1024
and recompile. 
The error also exists.

**Comment by huchinlp** [comment]
Can you tell me the memory usage when during training?
Or the output of `nvidia-smi`?

**Comment by zqp2009happy** [comment]
Here is 
#define MIN_BLOCK_SIZE_FOR_MEMPOOL 256 * 1024 * 1024 (When I change 256 to 1024, it pushes the same error but nvidia-smi can not capture any variety. )
nvidia-smi : 
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:08:00.0 Off |                  N/A |
| 26%   37C    P2   173W / 250W |  10328MiB / 11178MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by huchinlp** [comment]
It's an OOM error.
We will optimize the memory efficiency in the next version.

**Comment by huchinlp** [comment]
The memory leak during training was fixed in the latest version.
