### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by hctian713** [NiuTrans/NiuTrans.NMT#8]
Hi！Nice work！ 
I wanna know where i can download Chinese-English parallel dataset, which containing 100,000 entries each in Chinese and English？

**Comment by Lucky-259** [comment]
> Hi！Nice work！ I wanna know where i can download Chinese-English parallel dataset, which containing 100,000 entries each in Chinese and English？

Thanks for your interest!  The data you mentioned is in the _NiuTrans/NiuTrans.SMT_ project, unzip the _sample.tar.gz_ and you can find it in the _sample-submission-version/TM-training-set_ folder.

You can check the link [https://github.com/NiuTrans/NiuTrans.SMT/tree/master/sample-data](https://github.com/NiuTrans/NiuTrans.SMT/tree/master/sample-data)

**Comment by hctian713** [comment]
Thanks for ur reply！
